PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX edam:<http://edamontology.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?data ?label ?property WHERE
{
  
    ?data rdfs:subClassOf+ edam:data_0006 .
    ?data rdfs:label ?label .

    #VALUES ?property { edam:is_format_of
    #                    }
    FILTER NOT EXISTS { ?format rdfs:subClassOf ?restriction . 
                        ?restriction rdf:type owl:Restriction ; 
                        owl:onProperty  edam:is_format_of; 
                        owl:someValuesFrom ?data.
                        }
    
}ORDER BY ?entity